services:
  backend:
    build:
      context: .
      dockerfile: deploy/Dockerfile.backend
    container_name: backend
    env_file:
      - .env
    entrypoint: /bin/bash
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    command: ["/app/backend.sh"]
    environment:
      - PYTHONPATH=/app/src
    volumes:
    - ./src:/app/src

  frontend:
    build:
      context: .
      dockerfile: deploy/Dockerfile.frontend
    container_name: frontend
    env_file:
      - .env
    entrypoint: /bin/bash
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - PYTHONPATH=/app/src
    command: ["/app/frontend.sh"]
    volumes:
    - ./src:/app/src

  llm:
    build:
      context: .
      dockerfile: deploy/Dockerfile.llm
    container_name: llm_image
    env_file:
      - .env
    entrypoint: /bin/bash
    ports:
      - "${LLM_PORT}:${LLM_PORT}"
    command: ["/app/llm.sh"]
    environment:
      - PYTHONPATH=/app/src
    volumes:
    - ./src:/app/src

volumes:
  frontend:
  backend:
  llm: