FROM python:3.9-slim-buster

WORKDIR /app

COPY ./requirements/front_req.txt /app/front_req.txt
COPY ./runners/frontend.sh /app/frontend.sh
COPY ./.env /app/.env

RUN pip install --no-cache-dir --upgrade -r /app/front_req.txt

COPY /src/app.py /app/app.py

RUN chmod +x /app/frontend.sh